targets = [
    { name = "snake", repo = "joaovitorclark/snake", spec_dir = "docs/specs" },
]

[project]
name = "snake"
language = "pt-BR"
project_url = "https://github.com/users/joaovitorclark/projects/14"
project_id = "PVT_kwHOBHNr6M4Bkm4N"

[github]
repo = "joaovitorclark/snake"

[status]
field_id = "PVTSSF_lAHOBHNr6M4Bkm4NzhjW4j8"
Todo = "6f79a5b6"
"In Progress" = "f44ee442"
Done = "1d3c907f"
Draft = "c12cc06b"
Ready = "f034bef5"
